# Generated by Django 2.2.12 on 2021-10-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=30)),
                ('jaddress', models.CharField(max_length=30)),
                ('jletter', models.FileField(max_length=30, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorCitizenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scname', models.CharField(max_length=30)),
                ('scage', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='loginmodel',
            options={'verbose_name': 'STUDENT MODEL'},
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='cfees',
            field=models.FileField(max_length=30, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='cphoto',
            field=models.FileField(max_length=30, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='loginmodel',
            table='AMTSAPP',
        ),
    ]
